---
created_at: 2017-09-17T01:58:08+0900
published_at: 2017-09-17T01:58:08+0900
updated_at: 2017-09-18T17:47:54+0900
format: article2019
title: "Rust でエラー型に Clone が実装されていてほしい"
tags:
  - prog-rust
  - tsurapoyo
kind: article

excerpt: "Rust でエラー型に Clone trait が実装されていてほしい理由とか愚痴とか。"
---
<?xml version="1.0"?>
<article
	xmlns="https://www.cardina1.red/_ns/doc2019"
	xmlns:xl="http://www.w3.org/1999/xlink"
	xml:id="article-2017-09-15-rust-clonable-error-types"
	xml:lang="ja"
	version="0.1"
>
<title>Rust でエラー型に Clone が実装されていてほしい</title>

<p>
	これは物申す系の話とかではなく、単なる愚痴。
	現状については<xref linkend="current-status" />セクション参照。
</p>

<section xml:id="abstract">
	<title>概要</title>
	<ul>
		<li>
			エラー云々以前に、ユーザが後から (<code>Clone</code> 等、自前でない trait の)実装を追加できない<footnote xml:id="footnote-trait-coherence" refmark-id="ref-footnote-trait-coherence">
				<link xl:href="http://qnighy.hatenablog.com/entry/2017/07/20/220000">Rustのコヒーレンス - 簡潔なQ</link>
			</footnote>以上、ライブラリ作者はできるだけ基本的な trait 群を derive しておくべきである。
		</li>
		<li>
			エラー型のオブジェクトを clone したい場合が存在する。
		</li>
		<li>
			<link xl:href="https://crates.io/crates/error-chain">error_chain</link> crate でエラー型を用意すると、現状(<link xl:href="https://crates.io/crates/error-chain/0.11.0">0.11.0</link> (<time datetime="2017-09-06">2017-09-06</time> リリース)時点)では <code>derive(Clone)</code> できない。
		</li>
	</ul>

	<p>
		以上のような理由で、つらい。
	</p>
</section>

<section xml:id="situations">
	<title>エラーを clone したい状況</title>

	<section xml:id="returning-result-from-iterator">
		<title>処理の完了や致命的な失敗の後にも、 Result を返す関数の呼び出しに制約をかけたくない場合</title>
		<p>
			たとえば XML パーサである xml-rs crate 等が該当する。
			<link xl:href="https://docs.rs/xml-rs/0.6.1/xml/reader/struct.EventReader.html#method.next"><code>xml::reader::EventReader::next()</code></link> は、(致命的な)パースエラー等があると <code>Err</code> を返すが、エラーが返された後も <code>next()</code> 自体は制限なく何度でも呼び出すことができる。
		</p>
		<blockquote cite="https://docs.rs/xml-rs/0.6.1/xml/reader/struct.EventReader.html#method.next">
			<p>
				If returned event is <code>XmlEvent::Error</code> or <code>XmlEvent::EndDocument</code>, then further calls to this method <strong>will return this event again</strong>.
			</p>
			<footer>
				<link xl:href="https://docs.rs/xml-rs/0.6.1/xml/reader/struct.EventReader.html#method.next">xml-rs 0.6.1 のドキュメント</link> より。
				<comment>強調は引用者による。</comment>
			</footer>
		</blockquote>
		<p>
			このような場合、最後のエラーを複数回返す必要が出てくるため、当然エラー型は <code>Clone</code> を実装していてほしい。
		</p>
		<p>
			以前、私が xml-rs を参考に書いた <link xl:href="https://crates.io/crates/fbx_direct">fbx_direct</link> crate では、エラーとして I/O エラー (<link xl:href="https://doc.rust-lang.org/std/io/struct.Error.html"><code>std::io::Error</code></link>) が有り得たため、<link xl:href="https://docs.rs/fbx_direct/0.6.2/src/fbx_direct/reader/error.rs.html#89-104">自前で <code>Clone</code> を実装することになってしまった</link>。
			Qiita の記事『<link xl:href="http://qiita.com/lo48576/items/8873866b8e7edf477985">Rustで std::io::Error をcloneしたいとき - Qiita</link>』はこのときの副産物である。
		</p>
		<p>
			完了や失敗の後の関数呼び出しに制約をかけるというのもひとつの選択で、たとえば <link xl:href="https://crates.io/crates/futures">futures-rs</link> などはその選択を採っている。
		</p>
		<blockquote cite="https://docs.rs/futures/0.1.16/futures/future/trait.Future.html#tymethod.poll">
			<p>
				<strong>Once a future has completed</strong> (returned <code>Ready</code> or <code>Err</code> from poll),
				<strong>then any future calls to <code>poll</code> may panic</strong>, block forever, or otherwise cause wrong behavior.
				The <code>Future</code> trait itself provides no guarantees about the behavior of <code>poll</code> after a future has completed.
			</p>
			<footer>
				<link xl:href="https://docs.rs/futures/0.1.16/futures/future/trait.Future.html#tymethod.poll">futures-rs 0.1.16 のドキュメント <code>poll</code> 関数の項目</link>の Panics セクションより。
				<comment>強調は引用者による。</comment>
			</footer>
		</blockquote>
		<p>
			futures-rs の <code>Future</code> trait 自体は各ライブラリ開発者が各々の型に対して実装しうるものであり、エラー型も様々だから、実装を単純にするためにこのように定めたのであろう。
		</p>
	</section>

	<section xml:id="error-type-for-warnings">
		<title>エラー型を致命的でない警告に対して使いたい場合</title>

		<section xml:id="error-type-for-warnings--concept">
			<title>コンセプト (サンプルコード)</title>
			<p>
				致命的でない警告をエラーとして扱うかどうかユーザに委ねたい場合などがあり、この場合警告は <code>Error</code> trait を実装していると良い。
				<link xl:href="https://gist.github.com/anonymous/2ce762d67289613e4403c547d1153e67">コード例</link>を書いたので参照されたい (<link xl:href="https://play.rust-lang.org/?gist=2ce762d67289613e4403c547d1153e67&amp;version=stable">playground へのリンク</link>)。
			</p>
			<figure>
				<programlisting language="rust"><![CDATA[
    // Buy only clean and not broken items.
    assert_eq!(
        Err(ShoppingError::Warning(ShoppingWarning::Dirty(2))),
        buy(1, 2, |w| Err(w))
    );
]]></programlisting>
				<caption>
					商品が汚れていたり壊れていたら買い物をやめる例
					(<link xl:href="https://gist.github.com/anonymous/2ce762d67289613e4403c547d1153e67">ソースコード</link> より抜粋, <link xl:href="https://play.rust-lang.org/?gist=2ce762d67289613e4403c547d1153e67&amp;version=stable">playground へのリンク</link>)。
				</caption>
			</figure>
			<figure>
				<programlisting language="rust"><![CDATA[
    // Buy not broken items, allow dirty items.
    assert_eq!(
        Ok(2),
        buy(1, 2, |w| {
            if let ShoppingWarning::Broken = w {
                Err(w)
            } else {
                Ok(())
            }
        })
    );
    // Buy not broken items, allow dirty items.
    assert_eq!(
        Err(ShoppingError::Warning(ShoppingWarning::Broken)),
        buy(2, 2, |w| {
            if let ShoppingWarning::Broken = w {
                Err(w)
            } else {
                Ok(())
            }
        })
    );
]]></programlisting>
				<caption>
					商品が汚れていても買うが、壊れていたら買い物をやめる例
					(<link xl:href="https://gist.github.com/anonymous/2ce762d67289613e4403c547d1153e67">ソースコード</link> より抜粋, <link xl:href="https://play.rust-lang.org/?gist=2ce762d67289613e4403c547d1153e67&amp;version=stable">playground へのリンク</link>)。
				</caption>
			</figure>
			<figure>
				<programlisting language="rust"><![CDATA[
    // Buy not broken items, allow dirty items.
    // Log troubles.
    let mut troubles = Vec::new();
    assert_eq!(
        Err(ShoppingError::Warning(ShoppingWarning::Broken)),
        buy(2, 2, |w| {
            troubles.push(w.clone());
            if let ShoppingWarning::Broken = w {
                Err(w)
            } else {
                Ok(())
            }
        })
    );
    assert_eq!(
        troubles,
        vec![
            ShoppingWarning::Dirty(5),
            ShoppingWarning::Broken,
        ]
    );
]]></programlisting>
				<caption>
					商品が汚れていても買うが、壊れていたら買い物をやめ、それはさておきトラブルを外部に記録しておく例
					(<link xl:href="https://gist.github.com/anonymous/2ce762d67289613e4403c547d1153e67">ソースコード</link> より抜粋, <link xl:href="https://play.rust-lang.org/?gist=2ce762d67289613e4403c547d1153e67&amp;version=stable">playground へのリンク</link>)。
				</caption>
			</figure>
			<p>
				警告のエラー型が <code>Clone</code> を実装していてほしいのは、まさに最後の例のような場合である。
				エラーをどこかに記憶(複製)したのち確認したい場合、 <code>clone()</code> できてほしい<footnote xml:id="footnote-referring-without-cloning" refmark-id="ref-footnote-referring-without-cloning">
					どうしてもというなら、大抵のコンテナは挿入した要素やエントリへの参照を返してくれたり <code>Vec::last()</code> のような機能を持っているので、 <code>Clone</code> が実装されておらずともやりようはあるが、余計な手間がかかるし、そういう話をしているのではない
				</footnote>し、 <code>assert_eq!()</code> 等でテストをしたい場合には <code>Clone</code> 以外にも <code>PartialEq</code> なども必要になるから、 <code>Clone</code> に限らず基本的な trait はとにかく実装しておいてほしいということである。
			</p>
		</section>

		<section xml:id="error-type-for-warnings--fbxcel">
			<title>具体例: fbxcel crate (自作)</title>
			<p>
				先述の fbx_direct crate とは別に(というか改良して)、 <link xl:href="https://github.com/lo48576/fbxcel">fbxcel</link> という crate を開発していて、こちらでは、致命的ではないがおかしいデータについて <link xl:href="https://github.com/lo48576/fbxcel/blob/adf9fac0f313ad04cef9f626cd04157176e66d01/src/parser/binary/error.rs#L179-L246"><code>Warning</code> 型</link>で警告を発するようになっている。
				単なるロギングではなく、こうして専用の型のついたオブジェクトを経由させることで、このライブラリを利用するアプリケーションからも警告履歴を利用可能となる。
			</p>
			<figure>
				<mediaobject>
					<img src="fbx-tree-view-capture.png" alt="fbxcel が発した警告を、 fbxcel を利用するアプリケーションが自由に整形して表示できる。" />
				</mediaobject>
				<caption><link xl:href="https://github.com/lo48576/fbx-tree-view">fbx-tree-view</link> (GUI のビューア)で fbxcel が発した警告を表示した例 (画像下部)</caption>
			</figure>
			<note>
				<title>FBX と validation error</title>
				<p>
					FBX ファイル形式はプロプライエタリであり、データが valid であるか否かがそもそもわからない。
					よって、致命的でない限り、どのような予想外のデータであっても致命的なエラー扱いとするわけにはいかなかった。
				</p>
				<p>
					かといって、潜在的にエラーや不整合の原因となりうるデータを静かに無視するわけにもいかない。
					たとえば、 Blender の FBX exporter は boolean value を本来の <code>0x54</code> と <code>0x59</code> でなく <code>0x00</code> と <code>0x01</code> で吐くため、 FBX SDK では boolean 型のプロパティが無視され欠落する。
					これを寛容に解釈して許すか、 FBX SDK との解釈の違いを避けるためエラーとするかは、ライブラリのユーザに委ねられるべきである。
				</p>
				<p>
					また、 <link xl:href="https://github.com/lo48576/fbxcel/blob/adf9fac0f313ad04cef9f626cd04157176e66d01/src/parser/binary/event/mod.rs#L117-L119">fbxcel のコメントに記してある</link>ように、 Blender の FBX exporter はパディングが16バイトアラインされておらず、これも valid な FBX のみを想定するアプリケーションでファイルフッタを正しく読めない原因となりうる。
					フッタには特に有益な情報はないが、このエラーを許すか許さないかは目的によるから、ライブラリが中立であるためには無条件の拒否や無視を行うべきではない。
				</p>
			</note>
		</section>

		<section xml:id="error-type-for-warnings--fsck-xv6">
			<title>具体例: fsck-xv6 (自作)</title>
			<p>
				いつぞやの OS の授業の課題で <link xl:href="https://github.com/mit-pdos/xv6-public">xv6</link> のファイルシステムの validator (<link xl:href="https://gitlab.cardina1.red/lo48576/titech-1610-os/tree/homework/4/fsck-xv6">fsck-xv6</link>) を実装したことがあり、このときもファイルシステムエラーを表現するための型に <code>Error</code> trait を実装した。
			</p>
			<p>
				こちらは一般的な意味での「エラー」ではあるが、ファイルシステムの妥当性検証という性質上、ファイルシステムのエラーがそのままプログラムの継続不可能を意味するわけではない。
				よって、複数のエラーが発生すればそれらを全て列挙したり、或いは <code>Vec</code> 等のコンテナに溜めたりといった用途を想定することになる。
			</p>
			<figure>
				<figure>
					<programlisting language="rust"><![CDATA[
    let errors = fs::validate(target_file)
        .expect("Critical error happened and validation cannot be proceeded");
    if errors.is_empty() {
        println!("No errors detected.");
    } else {
        println!("Errors detected:");
        for err in errors {
            println!("{}", err);
        }
    }
]]></programlisting>
					<caption><link xl:href="https://gitlab.cardina1.red/lo48576/titech-1610-os/blob/homework/4/fsck-xv6/src/main.rs#L24-33"><filename>src/main.rs</filename>, <code>main</code> 関数内</link>より抜粋</caption>
				</figure>
				<figure>
					<programlisting language="rust"><![CDATA[
pub fn validate<P: AsRef<Path>>(path: P) -> io::Result<Vec<Error>> {
    let path = path.as_ref();
    let mut reader = BufReader::new(File::open(path)?);

    let mut errors = vec![];
]]></programlisting>
					<caption><link xl:href="https://gitlab.cardina1.red/lo48576/titech-1610-os/blob/homework/4/fsck-xv6/src/fs/mod.rs#L39-43"><filename>src/fs/mod.rs</filename>, トップレベル</link>より抜粋</caption>
				</figure>
				<figure>
					<programlisting language="rust"><![CDATA[
/// Validation error.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Error {
    BitmapMismatch { target: BlockIndex, expected: bool },
    DataBlockReferenceConflict { block: BlockIndex },
    DirectoryWithoutDot { inode: Inode },
    DirectoryWithoutDotdot { inode: Inode },
]]></programlisting>
					<caption><link xl:href="https://gitlab.cardina1.red/lo48576/titech-1610-os/blob/homework/4/fsck-xv6/src/fs/error.rs#L9-15"><filename>src/fs/error.rs</filename>, トップレベル</link>より抜粋</caption>
				</figure>
				<caption>エラー型の実装</caption>
			</figure>
			<p>
				この設計は fbxcel のエラー処理の発想をそのまま使ったものであり、ゆえに結局警告をエラーとして使いたいのかそうでないのかよくわからない設計になっている。
				今の私が同じような目的のコードを書いたら、<link linkend="error-type-for-warnings--concept">最初の例</link>のように特定の警告にフックをかけて処理を中断できるように作るはずである。
			</p>
		</section>
	</section>
</section>

<section xml:id="current-status">
	<title>現状</title>
	<p>
		ここまで熟々と書いてきたのは、つまるところエラーを clone したいというだけの話である。
		現状でそれを妨げる要因は、以下のようなものである。
	</p>

	<section xml:id="std-io-error-doesnt-implement-clone">
		<title>std::io::Error が Clone を実装していない</title>
		<p>
			悲しいことに、そうなのである。
		</p>
		<p>
			<link xl:href="https://github.com/rust-lang/rust/issues/24135">issue が立ってはいる</link>が進展の様子はなく、当面は <link xl:href="http://qiita.com/lo48576/items/8873866b8e7edf477985">Qiita に書いた</link>ように誤魔化しつつやっていくしかない。
		</p>
	</section>

	<section xml:id="error-chain-doesnt-support-derive-on-the-error">
		<title>error-chain trait がエラー型に対する derive をサポートしていない</title>
		<p>
			<link xl:href="https://crates.io/crates/error-chain">error-chain</link> crate は、エラー型や関連する諸々を用意する際のボイラープレートを減らすためのライブラリである。
			イマドキ手書きの温かみのあるエラー型を書いたりしないよね、 error-chain は人権だよねという空気がある<sup>[要出典]</sup>が、残念ながら error-chain で定義したエラー型は <code>Clone</code> を実装していないのである！！！
			(<time datetime="2017-09-17">2017-09-17 時点</time>)
		</p>
		<p>
			<link xl:href="https://github.com/rust-lang-nursery/error-chain/pull/163">プルリクエスト</link>もあり議論は進んでいるようだが、今使いたい私にとっては重大な問題である<footnote xml:id="footnote-not-using-error-chain" refmark-id="ref-footnote-not-using-error-chain">
				error-chain を使わなければ良いではないかという話はその通りで、私も(まさに <code>Clone</code> を実装したいという理由で)今まで使わずにやってきたのだが、つらい。ボイラープレートつらい。
			</footnote>。
		</p>
	</section>
</section>

<section xml:id="references">
	<title>参考リンク</title>
	<ul>
		<li>
			<link xl:href="https://crates.io/crates/error-chain">error-chain</link>
			<ul>
				<li>
					<link xl:href="https://github.com/rust-lang-nursery/error-chain/issues/134">Allow deriving traits on the Error · Issue #134 · rust-lang-nursery/error-chain</link>
				</li>
				<li>
					<link xl:href="https://github.com/rust-lang-nursery/error-chain/pull/163">[WIP] Add derive block for deriving additional traits on error types by pengowen123 · Pull Request #163 · rust-lang-nursery/error-chain</link>
				</li>
			</ul>
		</li>
		<li>
			<link xl:href="https://github.com/rust-lang/rust/issues/24135">Consider changing io::Error to use Arc so it can implement Clone · Issue #24135 · rust-lang/rust</link>
		</li>
		<li>
			<link xl:href="http://qiita.com/lo48576/items/8873866b8e7edf477985">Rustで std::io::Error をcloneしたいとき - Qiita</link>
		</li>
	</ul>
</section>

</article>
